# Generated by Django 2.2.3 on 2019-08-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BujaMovies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='language',
            field=models.CharField(default='lang', max_length=3, null=True, verbose_name='Language'),
        ),
    ]
