# Generated by Django 2.2.3 on 2019-08-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BujaMovies', '0002_auto_20190826_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='slug',
            field=models.SlugField(max_length=30, null=True, unique=True),
        ),
    ]
