# Generated by Django 2.2.3 on 2019-08-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BujaMovies', '0003_films_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='disliké',
        ),
        migrations.RemoveField(
            model_name='avis',
            name='liké',
        ),
        migrations.RemoveField(
            model_name='avis',
            name='titre',
        ),
        migrations.AddField(
            model_name='avis',
            name='likes',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avis',
            name='slug_key',
            field=models.TextField(default='0', verbose_name='Slug key'),
            preserve_default=False,
        ),
    ]
