# Generated by Django 2.2.3 on 2019-08-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BujaMovies', '0004_auto_20190827_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='slug_key',
            field=models.TextField(unique=True, verbose_name='Slug key'),
        ),
    ]
