# Generated by Django 2.2.3 on 2019-08-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BujaMovies', '0005_auto_20190827_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='likes',
            field=models.BooleanField(default=True),
        ),
    ]
