# Generated by Django 2.2.3 on 2019-09-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BujaMovies', '0009_auto_20190902_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='slug_key',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Slug key'),
        ),
    ]
