# Generated by Django 2.2.3 on 2019-09-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BujaMovies', '0010_auto_20190902_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='unlikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='avis',
            name='likes',
            field=models.IntegerField(default=1),
        ),
    ]
