# Generated by Django 2.2.3 on 2019-09-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BujaMovies', '0011_auto_20190903_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='avis',
            name='slug_key',
            field=models.CharField(max_length=50, verbose_name='Slug key'),
        ),
    ]
