# Generated by Django 2.2.3 on 2019-09-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BujaMovies', '0012_auto_20190903_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relations',
        ),
    ]
