# Generated by Django 2.2.3 on 2019-09-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BujaMovies', '0013_delete_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='Movies/', verbose_name='Cover'),
        ),
    ]
