# Generated by Django 2.2.3 on 2019-09-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BujaMovies', '0014_films_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
