# Generated by Django 2.2.3 on 2019-09-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BujaMovies', '0015_auto_20190903_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='Movies/'),
        ),
    ]
