# Generated by Django 2.2.3 on 2019-09-03 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BujaMovies', '0016_auto_20190903_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avis',
            old_name='unlikes',
            new_name='dislikes',
        ),
    ]
