# Generated by Django 2.2.3 on 2019-09-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BujaMovies', '0017_auto_20190903_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='film',
            field=models.FileField(blank=True, null=True, upload_to='Videos/'),
        ),
        migrations.AlterField(
            model_name='films',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='Covers/'),
        ),
    ]
